services:
  naiveproxy:
    build: .
    container_name: naiveproxy
    restart: unless-stopped
    ports:
      - "443:443"        # напрямую, без Traefik
    environment:
      DOMAIN: ${DOMAIN}
      EMAIL: ${EMAIL}
      PROXY_USER: ${PROXY_USER}
      PROXY_PASS: ${PROXY_PASS}
      MASK_SITE: ${MASK_SITE:-https://demo.cloudreve.org}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - dokploy-network
volumes:
  caddy_data:
  caddy_config:
networks:
  dokploy-network:
    external: true